### ISSUE TITLE
Custom Profile has only certain allowed values for ncpus

### ISSUE THREAD

**Issue by hrzepa** [ImperialCollegeLondon/hpc_portal#16]
A custom job script of the type

#PBS -q express
#PBS -P exp-00049

only allows certain values of ncpus. I submitted with ncpus=16 which is not allowed.  As far as  I can see, the only allowed values are  32 and  256.  Ideally, upon detecting #PBS -q express  in a job script, the  AI should show only these values of ncpus, to prevent an invalid combination from being submitted.

**Comment by hrzepa** [comment]
I did try creating a custom configuration for this instance.  Unfortunately, the custom code was overwritten by the template code and so it did not work.   So  a solution is still needed for us to run EXPRESS jobs invoking eg  256 processors.

**Comment by cc-a** [comment]
I can think of two options.
1) We make custom configurations a full alternative to resource specifications. User would then select either a resource spec or a custom config rather than both. It would be entirely up to the user to provide a valid configuration that includes the necessary resource specifications.
2) We allow users to add their own custom resource specifications. Once added these would then appear in the resources drop down menu. These could then be used in combination with a custom configuration or not as the user desires.

Overall I think 2 is better as it is more flexible, 1 would require that users create a new configuration for every combination of resources with express queue access.

**Comment by hrzepa** [comment]
Yes, lets go for 2.

**Comment by cc-a** [comment]
Implemented by 78ba6d27a6efb6c9030192fdaefffa64385be4ce. Please give it a go.

**Comment by hrzepa** [comment]
Suggestions for labels to help the user map one menu to another.

In https://openondemand.rcs.ic.ac.uk/pun/sys/chemistry_portal/job_type/
we have 
**"Job resources"**
and
**"Custom configuration"** 
in that order.

In https://openondemand.rcs.ic.ac.uk/pun/sys/chemistry_portal/profile/ the order is reversed and the labels are somewhat different
**"Custom Job Script Configurations (Advanced)"**
and 
**"Custom Resource Configurations (Advanced)"**

Can we normalise the labels?  Thus in https://openondemand.rcs.ic.ac.uk/pun/sys/chemistry_portal/profile/
**"Job resources (advanced)"**
and 
**"Custom configuration (advanced)"**
in that order.

Perhaps an example of each might be included in the text, ie

**#PBS -l select=1:ncpus=256:mem=800gb,walltime=72:00:00**

and

**#PBS -q express
#PBS -P exp-000XX**

to help clarify what belongs where.

**Comment by hrzepa** [comment]
Chris,

Suggestions added to  issue #16

Thanks for the implementation!
