### ISSUE TITLE
Server Error (500)  

### ISSUE THREAD

**Issue by hrzepa** [ImperialCollegeLondon/hpc_portal#50]
From https://openondemand.rcs.ic.ac.uk/pun/sys/chemistry_portal/list_jobs/  

for the last 14 hours or so.

**Comment by cc-a** [comment]
Should be cleared up now. As I've mentioned previously the user databases are currently stored on the RDS over an NFS mount. This issue seems to have been caused by your database getting into a funny locked state which can happen when accessing an sqlite db over NFS. This is something that would inevitably reoccur in the long run with more users so this is a good reason to move the database location off of the RDS. As we've discussed previously this would also help to decouple the responsiveness of the portal from RDS performance.

**Comment by hrzepa** [comment]
Thanks.  What are the plans to move the database off the  RDS?  Any decisions we need to take?

**Comment by cc-a** [comment]
No shouldn't make any difference to the portal, just requires some config changes to the machine that hosts it.

**Comment by cc-a** [comment]
I'll take a look at this now. The portal will probably be unusable for a bit.

**Comment by cc-a** [comment]
The databases have now been moved to the filesystem of the portal host machine. Hopefully this will improve the stability somewhat.
